"""Initial migration

Revision ID: 03d24dbeb689
Revises: 
Create Date: 2026-06-12 07:09:06.258705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03d24dbeb689'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text('CREATE SCHEMA IF NOT EXISTS "crm"'))
    op.create_table('users',

    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='user_role', schema='crm', create_constraint=True), server_default='USER', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name='uq_users_username'),
    schema='crm'
    )
    op.create_index('idx_users_username', 'users', ['username'], unique=False, schema='crm')
    op.create_table('contacts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('middle_name', sa.String(length=120), nullable=True),
    sa.Column('full_name', sa.String(length=320), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'LEAD', 'ACTIVE', 'CUSTOMER', 'INACTIVE', 'LOST', name='contact_status', schema='crm', create_constraint=True), server_default='NEW', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['crm.users.id'], name=op.f('fk_contacts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts')),
    sa.UniqueConstraint('id', 'user_id', name='uq_contacts_id_user_id'),
    schema='crm'
    )
    op.create_index('idx_contacts_full_name', 'contacts', ['full_name'], unique=False, schema='crm')
    op.create_index('idx_contacts_user_id', 'contacts', ['user_id'], unique=False, schema='crm')
    op.create_index('idx_contacts_user_status', 'contacts', ['user_id', 'status'], unique=False, schema='crm')
    op.create_table('mcp_keys',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('key_hash', sa.Text(), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['crm.users.id'], name=op.f('fk_mcp_keys_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mcp_keys')),
    sa.UniqueConstraint('key_hash', name='uq_mcp_keys_key_hash'),
    schema='crm'
    )
    op.create_index('idx_mcp_keys_active', 'mcp_keys', ['is_active'], unique=False, schema='crm')
    op.create_index('idx_mcp_keys_key_hash', 'mcp_keys', ['key_hash'], unique=False, schema='crm')
    op.create_index('idx_mcp_keys_user_id', 'mcp_keys', ['user_id'], unique=False, schema='crm')
    op.create_table('contact_addresses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['crm.contacts.id'], name=op.f('fk_contact_addresses_contact_id_contacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_addresses')),
    schema='crm'
    )
    op.create_index('idx_contact_addresses_contact_id', 'contact_addresses', ['contact_id'], unique=False, schema='crm')
    op.create_index('idx_contact_addresses_primary', 'contact_addresses', ['contact_id'], unique=True, schema='crm', postgresql_where=sa.text('is_primary IS TRUE'))
    op.create_table('contact_emails',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['crm.contacts.id'], name=op.f('fk_contact_emails_contact_id_contacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_emails')),
    sa.UniqueConstraint('contact_id', 'email', name='uq_contact_emails_contact_email'),
    schema='crm'
    )
    op.create_index('idx_contact_emails_contact_id', 'contact_emails', ['contact_id'], unique=False, schema='crm')
    op.create_index('idx_contact_emails_email', 'contact_emails', ['email'], unique=False, schema='crm')
    op.create_index('idx_contact_emails_primary', 'contact_emails', ['contact_id'], unique=True, schema='crm', postgresql_where=sa.text('is_primary IS TRUE'))
    op.create_table('contact_notes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id', 'user_id'], ['crm.contacts.id', 'crm.contacts.user_id'], name='fk_contact_notes_contact_user_contacts', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['crm.users.id'], name=op.f('fk_contact_notes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_notes')),
    schema='crm'
    )
    op.create_index('idx_contact_notes_contact_id', 'contact_notes', ['contact_id'], unique=False, schema='crm')
    op.create_index('idx_contact_notes_user_id', 'contact_notes', ['user_id'], unique=False, schema='crm')
    op.create_table('contact_phones',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['crm.contacts.id'], name=op.f('fk_contact_phones_contact_id_contacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_phones')),
    sa.UniqueConstraint('contact_id', 'phone', name='uq_contact_phones_contact_phone'),
    schema='crm'
    )
    op.create_index('idx_contact_phones_contact_id', 'contact_phones', ['contact_id'], unique=False, schema='crm')
    op.create_index('idx_contact_phones_phone', 'contact_phones', ['phone'], unique=False, schema='crm')
    op.create_index('idx_contact_phones_primary', 'contact_phones', ['contact_id'], unique=True, schema='crm', postgresql_where=sa.text('is_primary IS TRUE'))
    op.create_table('contact_tags',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=False),
    sa.Column('tag', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id', 'user_id'], ['crm.contacts.id', 'crm.contacts.user_id'], name='fk_contact_tags_contact_user_contacts', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['crm.users.id'], name=op.f('fk_contact_tags_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_tags')),
    sa.UniqueConstraint('user_id', 'contact_id', 'tag', name='uq_contact_tags_user_contact_tag'),
    schema='crm'
    )
    op.create_index('idx_contact_tags_contact_id', 'contact_tags', ['contact_id'], unique=False, schema='crm')
    op.create_index('idx_contact_tags_user_id', 'contact_tags', ['user_id'], unique=False, schema='crm')
    op.create_table('deals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), server_default='RUB', nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'NEGOTIATION', 'PROPOSAL_SENT', 'WAITING_RESPONSE', 'WON', 'LOST', 'CANCELLED', name='deal_status', schema='crm', create_constraint=True), server_default='NEW', nullable=False),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id', 'user_id'], ['crm.contacts.id', 'crm.contacts.user_id'], name='fk_deals_contact_user_contacts', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['crm.users.id'], name=op.f('fk_deals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deals')),
    schema='crm'
    )
    op.create_index('idx_deals_contact_id', 'deals', ['contact_id'], unique=False, schema='crm')
    op.create_index('idx_deals_user_id', 'deals', ['user_id'], unique=False, schema='crm')
    op.create_index('idx_deals_user_status', 'deals', ['user_id', 'status'], unique=False, schema='crm')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_deals_user_status', table_name='deals', schema='crm')
    op.drop_index('idx_deals_user_id', table_name='deals', schema='crm')
    op.drop_index('idx_deals_contact_id', table_name='deals', schema='crm')
    op.drop_table('deals', schema='crm')
    op.drop_index('idx_contact_tags_user_id', table_name='contact_tags', schema='crm')
    op.drop_index('idx_contact_tags_contact_id', table_name='contact_tags', schema='crm')
    op.drop_table('contact_tags', schema='crm')
    op.drop_index('idx_contact_phones_primary', table_name='contact_phones', schema='crm', postgresql_where=sa.text('is_primary IS TRUE'))
    op.drop_index('idx_contact_phones_phone', table_name='contact_phones', schema='crm')
    op.drop_index('idx_contact_phones_contact_id', table_name='contact_phones', schema='crm')
    op.drop_table('contact_phones', schema='crm')
    op.drop_index('idx_contact_notes_user_id', table_name='contact_notes', schema='crm')
    op.drop_index('idx_contact_notes_contact_id', table_name='contact_notes', schema='crm')
    op.drop_table('contact_notes', schema='crm')
    op.drop_index('idx_contact_emails_primary', table_name='contact_emails', schema='crm', postgresql_where=sa.text('is_primary IS TRUE'))
    op.drop_index('idx_contact_emails_email', table_name='contact_emails', schema='crm')
    op.drop_index('idx_contact_emails_contact_id', table_name='contact_emails', schema='crm')
    op.drop_table('contact_emails', schema='crm')
    op.drop_index('idx_contact_addresses_primary', table_name='contact_addresses', schema='crm', postgresql_where=sa.text('is_primary IS TRUE'))
    op.drop_index('idx_contact_addresses_contact_id', table_name='contact_addresses', schema='crm')
    op.drop_table('contact_addresses', schema='crm')
    op.drop_index('idx_mcp_keys_user_id', table_name='mcp_keys', schema='crm')
    op.drop_index('idx_mcp_keys_key_hash', table_name='mcp_keys', schema='crm')
    op.drop_index('idx_mcp_keys_active', table_name='mcp_keys', schema='crm')
    op.drop_table('mcp_keys', schema='crm')
    op.drop_index('idx_contacts_user_status', table_name='contacts', schema='crm')
    op.drop_index('idx_contacts_user_id', table_name='contacts', schema='crm')
    op.drop_index('idx_contacts_full_name', table_name='contacts', schema='crm')
    op.drop_table('contacts', schema='crm')
    op.drop_index('idx_users_username', table_name='users', schema='crm')
    op.drop_table('users', schema='crm')
    op.execute(sa.text('DROP SCHEMA IF EXISTS "crm" CASCADE'))
    # ### end Alembic commands ###

